version: '3'

volumes:
  pg_data:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: artemiiru/alfabank_hackathon:latest
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/backend_static
      - ./.env:/app
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media1:/usr/share/nginx/html
      - static_volume:/static
    depends_on:
      - backend
