"""add_relationship_pdp_task

Revision ID: 002
Revises: 001
Create Date: 2024-01-22 23:45:40.581364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('type_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('status_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_type_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_status_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'type', ['type_id'], ['id'])
    op.create_foreign_key(None, 'task', 'status', ['status_id'], ['id'])
    op.drop_column('task', 'status')
    op.drop_column('task', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_status_fkey', 'task', 'status', ['status'], ['id'])
    op.create_foreign_key('task_type_fkey', 'task', 'type', ['type'], ['id'])
    op.drop_column('task', 'status_id')
    op.drop_column('task', 'type_id')
    # ### end Alembic commands ###
