"""remove_remplate_dates

Revision ID: 004
Revises: 003
Create Date: 2024-01-25 17:00:28.606443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'starting_date')
    op.drop_column('template', 'deadline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('template', sa.Column('starting_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
