"""add_skills_table

Revision ID: 005
Revises: 004
Create Date: 2024-01-26 04:41:37.638334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('template_skill',
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], )
    )
    op.create_table('task_skill',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], )
    )
    op.drop_column('task', 'skills')
    op.drop_column('template', 'skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('skills', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('skills', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_table('task_skill')
    op.drop_table('template_skill')
    op.drop_table('skill')
    # ### end Alembic commands ###
