LENGTH_LIMITS_STRING_FIELDS = 100
LENGTH_LIMITS_STATUS_NAME_FIELD = 50
LENGTH_LIMITS_TEXT_FIELDS = 255
LENGTH_LIMITS_TYPE_NAME_FIELD = 50
LENGTH_LIMITS_USER_FIELDS = 150
LENGTH_LIMITS_LINK_FIELDS = 200
